language: objective-c
osx_image: xcode7.3
branches:
  only:
    - master
    - develop
before_install:
  - bundle install
  - instruments -s
script:
  - set -o pipefail
  - fastlane travis
  - danger --verbose
  - pod lib lint --quick
