language: objective-c
osx_image: xcode7.3
# branches:
#   only:
#     - master
before_install:
  - gem install bundler
  - bundle install
script:
  - set -o pipefail
  - fastlane travis
  - pod lib lint --quick
